# Generated by Django 5.1.7 on 2025-04-06 16:15

import CRYPTEX.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYPTEX', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unique_code',
            field=models.CharField(default=CRYPTEX.models.generate_unique_code, max_length=6, unique=True),
        ),
    ]
