# Generated by Django 5.1.7 on 2025-04-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYPTEX', '0002_alter_userprofile_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='CRYPTEX.userprofile'),
        ),
    ]
