# Generated by Django 5.1.7 on 2025-05-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRYPTEX', '0004_userprofile_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_seen',
        ),
    ]
