# Generated by Django 5.1.7 on 2025-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRYPTEX', '0005_remove_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_mfa',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
