# Generated by Django 5.1.7 on 2025-04-17 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0002_securefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 16, 43, 57, 463631, tzinfo=datetime.timezone.utc)),
        ),
    ]
