# Generated by Django 5.1.7 on 2025-04-17 17:32

import secure_channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0004_alter_securefile_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securefile',
            name='expired_at',
            field=models.DateTimeField(default=secure_channel.models.get_expiration_time),
        ),
    ]
