# Generated by Django 5.1.7 on 2025-04-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0005_alter_securefile_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securefile',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='securefile',
            name='encrypted_description',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
