# Generated by Django 5.1.7 on 2025-04-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0007_securefile_is_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secure_channel.securechannel'),
        ),
    ]
