# Generated by Django 5.1.7 on 2025-04-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0008_securefile_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
