# Generated by Django 5.1.7 on 2025-04-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0009_securefile_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securefile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
