# Generated by Django 5.1.7 on 2025-04-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0010_alter_securefile_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securefile',
            name='file_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
