# Generated by Django 5.1.7 on 2025-05-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0013_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='encrypted_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
