# Generated by Django 5.1.7 on 2025-05-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0014_securefile_encrypted_filename_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securefile',
            name='encrypted_filename',
        ),
    ]
