# Generated by Django 5.1.7 on 2025-05-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0015_remove_securefile_encrypted_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
