# Generated by Django 5.1.7 on 2025-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0018_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='encryption_version',
            field=models.CharField(default='v1', max_length=10),
        ),
    ]
