# Generated by Django 5.1.7 on 2025-05-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0019_securefile_encryption_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securechannel',
            name='aes_key_encrypted',
            field=models.TextField(),
        ),
    ]
