# Generated by Django 5.1.7 on 2025-05-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0020_alter_securechannel_aes_key_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bufferedfile',
            name='encrypted_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='securefile',
            name='encrypted_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
