# Generated by Django 5.1.7 on 2025-05-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0021_alter_bufferedfile_encrypted_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='encrypted_aes_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securefile',
            name='nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securefile',
            name='tag',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
