# Generated by Django 5.1.7 on 2025-05-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0022_securefile_encrypted_aes_key_securefile_nonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='desc_nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securefile',
            name='desc_tag',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
