# Generated by Django 5.1.7 on 2025-05-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0023_securefile_desc_nonce_securefile_desc_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securefile',
            name='encrypted_aes_key',
        ),
        migrations.AlterField(
            model_name='securechannel',
            name='aes_key_encrypted',
            field=models.BinaryField(),
        ),
    ]
