# Generated by Django 5.1.7 on 2025-05-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0024_remove_securefile_encrypted_aes_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securechannel',
            name='aes_key_encrypted',
        ),
        migrations.AddField(
            model_name='securechannel',
            name='encrypted_aes_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securefile',
            name='encrypted_aes_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
