# Generated by Django 5.1.7 on 2025-05-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_channel', '0025_remove_securechannel_aes_key_encrypted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securefile',
            name='encrypted_aes_key',
        ),
    ]
